ALTER TABLE t_p30184577_microfinance_website.loans
  ADD COLUMN IF NOT EXISTS signed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS signed_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS offer_amount NUMERIC(12,2) NULL,
  ADD COLUMN IF NOT EXISTS offer_days INTEGER NULL,
  ADD COLUMN IF NOT EXISTS offer_rate NUMERIC(6,4) NULL;