CREATE TABLE car_loan_applications (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255),
  birth_date VARCHAR(50),
  address TEXT,
  passport_serial VARCHAR(20),
  passport_num VARCHAR(20),
  passport_issued TEXT,
  car_brand VARCHAR(100),
  car_model VARCHAR(100),
  car_year INTEGER,
  car_mileage INTEGER,
  contact_person TEXT,
  card_number TEXT,
  loan_amount INTEGER NOT NULL DEFAULT 0,
  loan_months INTEGER NOT NULL DEFAULT 12,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  reject_reason TEXT,
  approved_amount INTEGER,
  approved_months INTEGER,
  approved_rate NUMERIC(5,2),
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);