CREATE TABLE shopping_loan_applications (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255),
  birth_date VARCHAR(50),
  address TEXT,
  passport_series VARCHAR(20),
  passport_number VARCHAR(20),
  passport_date VARCHAR(50),
  passport_by TEXT,
  snils VARCHAR(30),
  shop_name TEXT,
  item_name TEXT,
  item_price INTEGER,
  loan_amount INTEGER NOT NULL DEFAULT 0,
  loan_months INTEGER NOT NULL DEFAULT 12,
  contact_person TEXT,
  card_number TEXT,
  file_passport TEXT,
  file_registration TEXT,
  file_selfie TEXT,
  file_snils TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  reject_reason TEXT,
  approved_amount INTEGER,
  approved_months INTEGER,
  approved_rate NUMERIC(5,2),
  notes TEXT,
  contract_signed BOOLEAN DEFAULT FALSE,
  contract_signed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);